import Header from "./Header/Header";
import Footer from "./Footer/Footer";
import Imagecarousel from "./Imagecarousel/Imagecarousel";
import Ourservices from "./Ourservices/Ourservices";
import Aboutbeyondsyntax from "./Aboutbeyondsyntax/Aboutbeyondsyntax";
import Whywithus from "./Whywithus/Whywithus";
import Howcanwehelpyou from "./Howcanwehelpyou/Howcanwehelpyou";
import Ourtechnologies from "./Ourtechnologies/Ourtechnologies";
import Ourclients from "./Ourclients/Ourclients";
import Aboutbanner from "./Aboutusbanner/Aboutusbanner";
import Whypartnerwithus from "./Whypartnerwithus/Whypartnerwithus";
import Visionmission from "./Visionmission/Visionmission";
import Itstaffingbanner from "./Itstaffingbanner/Itstaffingbanner";
import Itstaffingcontent from "./Itstaffingcontent/Itstaffingcontent";
import Weoffer from "./Weoffer/Weoffer";
import RpoMps from "./RpoMps/RpoMps";
import Contactusbanner from "./Contactusbanner/Contactusbanner";
import Contactuscontent from "./Contactuscontent/Contactuscontent";
import Contactusform from "./Contactusform/Contactusform";

export { Header, Footer, Imagecarousel, Ourservices, Aboutbeyondsyntax, Whywithus, Howcanwehelpyou, Ourtechnologies, Ourclients, Aboutbanner, Whypartnerwithus, Visionmission, Itstaffingbanner, Itstaffingcontent, Weoffer, RpoMps, Contactusbanner, Contactuscontent, Contactusform,};