import Header from "./Header/Header";
import Footer from "./Footer/Footer";
import Imagecarousel from "./Imagecarousel/Imagecarousel";
import Ourservices from "./Ourservices/Ourservices";
import AboutFountainTech from "./AboutFountainTech/AboutFountainTech";
import Aboutbanner from "./Aboutusbanner/Aboutusbanner";
import Visionmission from "./Visionmission/Visionmission";
import Servicesbanner from "./Servicesbanner/Servicesbanner";
import Contactusbanner from "./Contactusbanner/Contactusbanner";
import Contactuscontent from "./Contactuscontent/Contactuscontent";
import Contactusform from "./Contactusform/Contactusform";
import TextComponent from "./TextComponent/TextComponent";
import GetTouch from "./GetTouch/GetTouch";
import ImageTextComponent from "./ImageTextComponent/ImageTextComponent";
export { Header, Footer, Imagecarousel, Ourservices,AboutFountainTech,Aboutbanner, Visionmission,Contactusbanner, Contactuscontent, Contactusform,TextComponent,Servicesbanner,GetTouch,ImageTextComponent};
